version: '3'
services:
  flask:
    build: .
    container_name: a_flask
    expose:
      - 3000
    volumes:
     - .:/app
    depends_on:
     - redis
    image: a_flask
    
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: a_redis

  nginx:
    build: ./nginx
    container_name: a_nginx
    ports:
     - "80:80"
     - "443:443"
    depends_on:
    - flask
    image: a_nginx
  # mysql container
  # mysql:
  #   image: mysql:5.7
  #   container_name: a_mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: {{ mysql_root_password }}
  #     MYSQL_DATABASE: main_db
  #     MYSQL_USER: {{ mysql_user }}
  #     MYSQL_PASSWORD: {{ mysql_password }}
  #   volumes:
  #     - ./mysql:/var/lib/mysql
