version: '3'
services:
  flask:
    build: .
    container_name: a_flask
    expose:
      - 3000
    volumes:
     - .:/app
    depends_on:
     - redis
    image: a_flask
    # 可以將此處改成該 image google cloud 地址
    
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: a_redis

  nginx:
    build: ./nginx
    container_name: a_nginx
    ports:
     - "80:80"
     - "443:443"
    depends_on:
    - flask
    image: a_nginx
    # 可以將此處改成該 image google cloud 地址
