# name: Flask Test

# on: [push]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.11.0
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install flask
#     - name: Test Flask app
#       run: |
#         python app.py
